(define-module (codemac packages systemd)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (gnu packages acl)
  #:use-module (gnu packages admin)
  #:use-module (gnu packages base)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages cryptsetup)
  #:use-module (gnu packages curl)
  #:use-module (gnu packages cyrus-sasl)
  #:use-module (gnu packages elf)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gnupg)
  #:use-module (gnu packages gperf)
  #:use-module (gnu packages libidn)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages m4)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages python)
  #:use-module (gnu packages tls)
  #:use-module (guix build gnu-build-system)
  #:use-module (guix build-system gnu)
  #:use-module (guix download)
  #:use-module (guix packages)
  #:export (systemd))

(define systemd
  (package
    (name "systemd")
    (version "221")
    (source (origin
              (method url-fetch)
              (uri (string-append "http://www.freedesktop.org/software/systemd/systemd-" version ".tar.xz"))
              (sha256
               (base32 "0kyca4nlf7rhfsq0b1im2247rg0zvfp5jd5irj4cdgxga230hph8"))))
    (build-system gnu-build-system)
    (arguments `(#:configure-flags
                 '("--localstatedir=/var"
                   "--sysconfdir=/etc"
                   "--with-sysvinit-path="
                   "--with-sysvrcnd-path=")
                 #:tests? #f))
    (native-inputs `(("pkg-config" ,pkg-config)
                     ("intltool" ,intltool)
                     ("gperf" ,gperf)
                     ("python" ,python)
                     ("libcap" ,libcap)
                     ("dbus" ,dbus)
                     ("util-linux" ,util-linux)
                     ("python-lxml" ,python-lxml)
                     ("which" ,which)
                     ("m4" ,m4)
                     ("curl" ,curl)
                     ("cryptsetup" ,cryptsetup)
                     ("zlib" ,zlib)
                     ("libidn" ,libidn)
                     ("libgcrypt" ,libgcrypt)
                     ("linux-pam" ,linux-pam)
                     ("acl" ,acl)
                     ("gnutls" ,gnutls)
                     ("iptables" ,iptables)
                     ("elfutils" ,elfutils)
                     ("openssl" ,openssl)
                     ("cyrus-sasl" ,cyrus-sasl)
                     ("shadow" ,shadow)
                     ("lvm2" ,lvm2)))
    (synopsis "systemd is a suite of basic building blocks for a Linux system.")
    (description "The reviled thing itself")
    (home-page "http://www.freedesktop.org/wiki/systemd")
    (license license:lgpl2.1+)))
